(defun is-regexp ( RE )
	( cond
		((atom RE) t)
		((equal '(car RE) 'seq) (mapcar (lambda (item)
																			( if (is-regexp item)
																					 (t)
																					 (return-from is-regexp nil)
																					)
																			) (cdr RE)))
	))
